version: '2'
services:
  haproxy:
    depends_on:
      - elasticsearch
      - kibana
      - logstash
    build: ./HAProxy
    image: elk-haproxy
    links:
      - elasticsearch
      - elasticsearch_master
      - kibana
      - logstash
    ports:
      - "5044:5044"
      - "5601:5601"
      - "9090:9090"
      - "9200:9200"
      - "10514:10514"
      - "10514:10514/udp"
    volumes:
    #   - "./.haproxy_cfg:/etc/haproxy/"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    restart: always
    environment:
      - "ES_BACKEND=elasticsearch"
      - "ES_BACKEND_PORT=9200"
      - "KIBANA_BACKEND=kibana"
      - "KIBANA_BACKEND_PORT=5601"
      - "LOGSTASH_BACKEND=logstash"
      - "BALANCE=roundrobin"
      - "SERVICE=haproxy"
      - "PROJECT=dockeransibleelkstack"

  elasticsearch_master:
    build: ./Elasticsearch
    image: elk-elasticsearch
    command: "elasticsearch -Des.node.master=true -Des.node.data=false"
    restart: always

  elasticsearch:
    depends_on:
      - elasticsearch_master
    image: elk-elasticsearch
    command: "elasticsearch -Des.discovery.zen.ping.unicast.hosts=elasticsearch_master"
    links:
      - elasticsearch_master
    volumes:
      - "./.data:/usr/share/elasticsearch/data"
    restart: always

  kibana:
    depends_on:
      - elasticsearch
    build: ./Kibana
    image: elk-kibana
    # links:
    #   - elasticsearch
    restart: always

  logstash:
    depends_on:
      - elasticsearch
    build: ./Logstash
    image: elk-logstash
    # links:
    #   - elasticsearch
    #   - haproxy
    restart: always
